[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Zshare-generics=y", "-C", "link-arg=-fuse-ld=mold"]

[target.x86_64-apple-darwin]
rustflags = ["-Zshare-generics=y"]

[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustflags = ["-Zshare-generics=y"]

[profile.dev]
debug = true
